import js from "@eslint/js";

export default [
  // Ignore bundled and lock files
  {
    ignores: ["site/orb-graph.bundle.js", "pnpm-lock.yaml", "node_modules/**"],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
      reportUnusedInlineConfigs: "error",
    },
    files: ["src/**/*.js", "site/**/*.js", "tests/**/*.mjs", "benchmarks/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        // Browser globals
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        WebSocket: "readonly",
        Worker: "readonly",
        EventTarget: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        indexedDB: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        queueMicrotask: "readonly",
        Promise: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        PerformanceObserver: "readonly",
        CSS: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLAnchorElement: "readonly",
        DOMParser: "readonly",
        performance: "readonly",
        getComputedStyle: "readonly",
        structuredClone: "readonly",
        WheelEvent: "readonly",
        Temporal: "readonly",
        L: "readonly", // Leaflet library
        console: "readonly",
        // Node (for tests/benchmarks)
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        global: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      // Strict error checking
      "no-console": ["error", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-undef": "error",
      "no-undefined": "off", // Modern undefined checks are valid; type/domain lint handles unsafe uncertainty
      "no-implicit-globals": "error",
      "no-implicit-coercion": "error",
      // Type safety (JSDoc checked by TypeScript)
      "no-var": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
      // Logic safety
      eqeqeq: ["error", "always"],
      "no-case-declarations": "error",
      "no-fallthrough": "error",
      "no-constant-condition": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-global-assign": "error",
      "no-with": "error",
      // Async/Promise safety
      "no-async-promise-executor": "error",
      "no-promise-executor-return": "error",
      // Array/Object safety
      "no-sparse-arrays": "error",
      "no-prototype-builtins": "error",
      // Best practices
      "no-param-reassign": ["error", { props: false }],
      "no-return-await": "error",
      "require-await": "off", // Not all promises need await
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-loss-of-precision": "error",
      "array-callback-return": ["error", { checkForEach: true }],
      "block-scoped-var": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      "guard-for-in": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-caller": "error",
      "no-constructor-return": "error",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-multi-assign": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-object-constructor": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-return-assign": ["error", "always"],
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "object-shorthand": ["error", "always"],
      "prefer-exponentiation-operator": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
      radix: "error",
      "symbol-description": "error",
      yoda: "error",
    },
  },
];
